### ISSUE TITLE
debug ipfs meet _cgo_try_pthread_create invalid conversion from ‘void*’ to ‘timespec*’

### ISSUE THREAD

**Issue by xiedeacc** [ipfs/go-ipfs#5761]
#### Version information:
go-ipfs version: 0.4.19-dev-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1

#### Description:
I want to debug ipfs use gdb or dlv, but it compiled by 
go build  -gcflags "all=-N -l" in [ipfs-project-root]/cmd/ipfs

it will prompts 

runtime/cgo
gcc_libinit.c: In function ‘int _cgo_try_pthread_create(pthread_t*, const pthread_attr_t*, void* (*)(void*), void*)’:
gcc_libinit.c:110:21: error: invalid conversion from ‘void*’ to ‘timespec*’ [-fpermissive]
   nanosleep(&ts, nil);
                     ^
In file included from /usr/include/pthread.h:24:0,
                 from gcc_libinit.c:8:
/usr/include/time.h:211:12: error:   initializing argument 2 of ‘int nanosleep(const timespec*, timespec*)’ [-fpermissive]
 extern int nanosleep (const struct timespec *__requested_time,

if compiled with (remove all), 

go build  -gcflags "-N -l" in [ipfs-project-root]/cmd/ipfs

things goes well but when use gdb or dlv to debug it, it cannot show any piece of code, just show:
1	_cgo_export.c: No such file or directory.

how to fix this??????

**Comment by Stebalien** [comment]
That build command works fine for me.

This looks like an issue with your compiler toolchain. Did you compile the go compiler yourself or are you using the pre-built binaries? I'd try recompiling the go compiler (or maybe updating gcc?).

Closing as this isn't a bug in go-ipfs. Feel free to ask followup questions but we're unlikely to be able to help much.

**Comment by xiedeacc** [comment]
yes after upgrade gcc from 4.8.5 to 7.3 ,fix this proble
